import 'package:flutter_test/flutter_test.dart';
import 'package:maid_kit/servers/maidcafe_install.dart';

void main() {
  test(
    'installer script encodes cloud credentials outside shell arguments',
    () {
      const secret = 'cloud-secret-with-"-quotes';
      final script = buildMaidCafeDaemonInstallScript(
        daemonId: 'daemon-1',
        cloudUrl: 'https://mk.solsynth.dev',
        cloudSecret: secret,
        artifactUrl: 'https://dist.example/maidcafe-daemon.tar',
      );

      expect(script, contains('curl --fail --location'));
      expect(script, contains('tar -xf "\$work_dir/maidcafe-daemon.tar"'));
      expect(script, contains('find "\$work_dir/extracted"'));
      expect(script, contains('/usr/local/bin/maidcafe-daemon'));
      expect(script, contains('/etc/maidcafe/config.toml'));
      expect(script, contains('printf \'%s\''));
      expect(script, contains('base64 -d'));
      expect(script, contains('systemctl enable --now maidcafe-daemon'));
      expect(script, contains('maidkit-managed'));
      expect(script, isNot(contains('git clone')));
      expect(script, isNot(contains('go build')));
      expect(script, isNot(contains(secret)));
      expect(
        script,
        isNot(contains('https://dist.example/maidcafe-daemon.tar')),
      );
    },
  );

  test('installer script escapes TOML values', () {
    final script = buildMaidCafeDaemonInstallScript(
      daemonId: 'daemon"quoted',
      cloudUrl: 'https://example.test/path?x=1',
      cloudSecret: 'secret',
      artifactUrl: 'https://dist.example/maidcafe-daemon.tar',
    );

    expect(script, isNot(contains('daemon"quoted')));
    expect(script, isNot(contains('https://example.test/path?x=1')));
    expect(script, contains('base64 -d'));
  });

  test('configuration updates are generated by MaidKit', () {
    final script = buildMaidCafeDaemonConfigScript(
      daemonId: 'maidkit-1',
      cloudUrl: '',
      cloudSecret: '',
      actions: const [
        MaidCafeActionDefinition(
          name: 'backup',
          command: '/usr/local/bin/backup',
          arguments: ['--mode', 'incremental'],
        ),
      ],
    );

    expect(script, contains('/etc/maidcafe/config.stdio.toml'));
    expect(script, contains('/etc/maidcafe/maidkit-managed'));
    expect(script, contains('base64 -d'));
    expect(script, isNot(contains('/usr/local/bin/maidcafe-daemon')));
  });

  test('stdio installer writes an SSH-stream daemon without systemd', () {
    final script = buildMaidCafeDaemonInstallScript(
      daemonId: 'daemon-1',
      cloudUrl: '',
      cloudSecret: '',
      artifactUrl: 'https://dist.example/maidcafe-daemon.tar',
      transport: 'stdio',
      actions: const [
        MaidCafeActionDefinition(
          name: 'backup',
          command: '/usr/local/bin/backup',
          arguments: ['--mode', 'incremental'],
        ),
      ],
    );

    expect(script, contains('/etc/maidcafe/config.stdio.toml'));
    expect(script, contains('install -o root -g root -m 0644'));
    expect(script, isNot(contains('systemctl enable --now maidcafe-daemon')));
    expect(script, contains('base64 -d'));
  });
}
