import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:maid_kit/servers/maidcafe_install.dart';

/// Decodes the daemon config.toml embedded in a generated install/update
/// script so tests can assert on the TOML the daemon will actually load.
String decodeMaidCafeConfigFromScript(String script) {
  final install = RegExp(
    r'''printf '%s' '([^']+)' \| base64 -d > "\$work_dir/config\.toml"''',
  ).firstMatch(script);
  if (install != null) {
    return utf8.decode(base64Decode(install.group(1)!));
  }
  final update = RegExp(
    r'''printf '%s' '([^']+)' \| base64 -d \| install''',
  ).firstMatch(script);
  if (update != null) {
    return utf8.decode(base64Decode(update.group(1)!));
  }
  fail('no embedded config.toml found in generated script');
}

void main() {
  test(
    'installer script encodes cloud credentials outside shell arguments',
    () {
      const secret = 'cloud-secret-with-"-quotes';
      final script = buildMaidCafeDaemonInstallScript(
        daemonId: 'daemon-1',
        cloudUrl: 'https://mk.solsynth.dev',
        cloudSecret: secret,
        artifactUrl: 'https://dist.example/maidcafe-daemon.tar',
        apiSecret: 'metrics-secret',
      );

      expect(script, contains('curl --fail --location'));
      expect(script, contains('tar -xf "\$work_dir/maidcafe-daemon.tar"'));
      expect(script, contains('find "\$work_dir/extracted"'));
      expect(script, contains('/usr/local/bin/maidcafe-daemon'));
      expect(script, contains('/etc/maidcafe/config.toml'));
      expect(script, contains('printf \'%s\''));
      expect(script, contains('base64 -d'));
      expect(script, contains('http://127.0.0.1:8747/health'));
      expect(script, contains('Authorization: Bearer \$metricsSecret'));
      expect(script, contains('systemctl restart maidcafe-daemon'));
      expect(script, contains('MaidCafe daemon did not become healthy.'));
      expect(script, contains('maidkit-managed'));
      expect(script, isNot(contains('git clone')));
      expect(script, isNot(contains('go build')));
      expect(script, isNot(contains(secret)));
      expect(
        script,
        isNot(contains('https://dist.example/maidcafe-daemon.tar')),
      );
    },
  );

  test('installer script escapes TOML values', () {
    final script = buildMaidCafeDaemonInstallScript(
      daemonId: 'daemon"quoted',
      cloudUrl: 'https://example.test/path?x=1',
      cloudSecret: 'secret',
      artifactUrl: 'https://dist.example/maidcafe-daemon.tar',
    );

    expect(script, isNot(contains('daemon"quoted')));
    expect(script, isNot(contains('https://example.test/path?x=1')));
    expect(script, contains('base64 -d'));
  });

  test('configuration updates are generated by MaidKit', () {
    final script = buildMaidCafeDaemonConfigScript(
      daemonId: 'maidkit-1',
      cloudUrl: '',
      cloudSecret: '',
      transport: 'http',
      actions: const [
        MaidCafeActionDefinition(
          name: 'backup',
          script: 'tar -czf /var/backups/site.tar.gz /srv/site',
        ),
      ],
    );

    expect(script, contains('/etc/maidcafe/config.toml'));
    expect(script, contains('/etc/maidcafe/maidkit-managed'));
    expect(script, contains('base64 -d'));
    expect(script, contains('systemctl restart maidcafe-daemon'));
    // The sync never downloads or installs the daemon binary; the only
    // reference is the ExecStart line of the reconciled systemd unit.
    expect(script, isNot(contains('curl --fail')));
    expect(script, isNot(contains('maidcafe-daemon.tar')));
    expect(script, contains('systemctl daemon-reload'));
    expect(script, contains('NoNewPrivileges=true'));
  });

  test(
    'configuration sync drops NoNewPrivileges when actions run as a user',
    () {
      final script = buildMaidCafeDaemonConfigScript(
        daemonId: 'maidkit-1',
        cloudUrl: '',
        cloudSecret: '',
        transport: 'http',
        actions: const [
          MaidCafeActionDefinition(
            name: 'deploy',
            script: 'echo hi',
            user: 'deploy',
          ),
        ],
      );

      expect(
        script,
        contains('# NoNewPrivileges: actions run as another user through sudo'),
      );
      expect(script, isNot(contains('NoNewPrivileges=true')));
      expect(script, contains('systemctl daemon-reload'));
    },
  );

  test('stdio installer writes an SSH-stream daemon without systemd', () {
    final script = buildMaidCafeDaemonInstallScript(
      daemonId: 'daemon-1',
      cloudUrl: '',
      cloudSecret: '',
      artifactUrl: 'https://dist.example/maidcafe-daemon.tar',
      transport: 'stdio',
      actions: const [
        MaidCafeActionDefinition(
          name: 'backup',
          script: 'tar -czf /var/backups/site.tar.gz /srv/site',
        ),
      ],
    );

    expect(script, contains('/etc/maidcafe/config.stdio.toml'));
    expect(script, contains('install -o root -g root -m 0644'));
    expect(script, isNot(contains('systemctl enable --now maidcafe-daemon')));
    expect(script, contains('base64 -d'));
  });

  test('rejects privileged HTTP ports', () {
    expect(
      () => buildMaidCafeDaemonInstallScript(
        daemonId: 'daemon-1',
        cloudUrl: '',
        cloudSecret: '',
        artifactUrl: 'https://dist.example/maidcafe-daemon.tar',
        port: 80,
      ),
      throwsArgumentError,
    );
  });

  test('actions derive an absolute command and deploy the body', () {
    const body =
        'tar -czf /var/backups/site.tar.gz /srv/site\n'
        'echo backup done';
    final script = buildMaidCafeDaemonInstallScript(
      daemonId: 'daemon-1',
      cloudUrl: '',
      cloudSecret: '',
      artifactUrl: 'https://dist.example/maidcafe-daemon.tar',
      actions: const [
        MaidCafeActionDefinition(
          name: 'backup',
          script: body,
          notifyOnSuccess: true,
        ),
      ],
    );

    expect(
      script,
      contains(
        'install -o root -g maidcafe -m 0750 /dev/stdin '
        '/etc/maidcafe/actions/backup.sh',
      ),
    );
    expect(
      script,
      contains('install -d -o root -g root -m 0755 /etc/maidcafe/actions'),
    );
    // The config records the deployed path and the script flag, never the
    // raw body.
    final config = decodeMaidCafeConfigFromScript(script);
    expect(config, contains('command = "/etc/maidcafe/actions/backup.sh"'));
    expect(config, contains('script = true'));
    expect(config, isNot(contains(body)));
    expect(config, contains('notifyOnSuccess = true'));
  });

  test('script deploy prepends a shebang and removes stale scripts', () {
    const body = 'printf "%s" ok\n';
    final snippet = buildMaidCafeActionScriptsScript(const [
      MaidCafeActionDefinition(name: 'backup', script: body),
    ], stdio: false);

    final deployed = RegExp(
      r"printf '%s' '([^']+)' \| base64 -d \| "
      r'install -o root -g maidcafe -m 0750 /dev/stdin '
      r'/etc/maidcafe/actions/backup\.sh',
    ).firstMatch(snippet);
    expect(deployed, isNotNull);
    final written = utf8.decode(base64Decode(deployed!.group(1)!));
    expect(written, startsWith('#!/bin/sh\n'));
    expect(written, contains(body));

    // An explicit shebang is preserved verbatim.
    const withShebang = '#!/usr/bin/env bash\nset -eu\n';
    final kept = buildMaidCafeActionScriptsScript(const [
      MaidCafeActionDefinition(name: 'keep', script: withShebang),
    ], stdio: false);
    expect(
      kept,
      contains('if [ "\$f" = "/etc/maidcafe/actions/keep.sh" ]; then'),
    );
    final keptMatch = RegExp(
      r"printf '%s' '([^']+)' \| base64 -d \| "
      r'install -o root -g maidcafe -m 0750 /dev/stdin '
      r'/etc/maidcafe/actions/keep\.sh',
    ).firstMatch(kept);
    expect(utf8.decode(base64Decode(keptMatch!.group(1)!)), withShebang);
  });

  test('stdio script deploy uses world-executable scripts', () {
    final snippet = buildMaidCafeActionScriptsScript(const [
      MaidCafeActionDefinition(name: 'backup', script: 'echo hi'),
    ], stdio: true);
    expect(
      snippet,
      contains(
        'install -o root -g root -m 0755 /dev/stdin '
        '/etc/maidcafe/actions/backup.sh',
      ),
    );
  });

  test('configuration updates deploy script bodies before restarting', () {
    const body = 'systemctl restart nginx';
    final script = buildMaidCafeDaemonConfigScript(
      daemonId: 'maidkit-1',
      cloudUrl: '',
      cloudSecret: '',
      transport: 'http',
      actions: const [
        MaidCafeActionDefinition(name: 'reload-nginx', script: body),
      ],
    );

    expect(script, contains('/etc/maidcafe/actions/reload-nginx.sh'));
    final configIndex = script.indexOf('config.toml');
    final restartIndex = script.indexOf('systemctl restart maidcafe-daemon');
    final deployIndex = script.indexOf('/etc/maidcafe/actions/');
    expect(configIndex, isNot(-1));
    expect(restartIndex, isNot(-1));
    // Scripts land between the config write and the daemon restart so the
    // freshly deployed body is what the restarted daemon loads.
    expect(deployIndex, greaterThan(configIndex));
    expect(deployIndex, lessThan(restartIndex));
    final config = decodeMaidCafeConfigFromScript(script);
    expect(
      config,
      contains('command = "/etc/maidcafe/actions/reload-nginx.sh"'),
    );
  });

  test('rejects actions with an empty script body', () {
    expect(
      () => buildMaidCafeDaemonConfigScript(
        daemonId: 'maidkit-1',
        cloudUrl: '',
        cloudSecret: '',
        transport: 'http',
        actions: const [MaidCafeActionDefinition(name: 'backup', script: '')],
      ),
      throwsArgumentError,
    );
  });

  test('rejects action names outside the daemon charset', () {
    expect(
      () => buildMaidCafeDaemonConfigScript(
        daemonId: 'maidkit-1',
        cloudUrl: '',
        cloudSecret: '',
        transport: 'http',
        actions: const [
          MaidCafeActionDefinition(name: 'bad name!', script: 'echo hi'),
        ],
      ),
      throwsArgumentError,
    );
  });

  test('extracts free-form template variables from action scripts', () {
    expect(
      maidCafeActionTemplateVariables(
        'systemctl restart {{ SERVICE_NAME }}\n'
        'echo {{ serviceName }} {{ SERVICE_NAME }}',
      ),
      ['SERVICE_NAME', 'serviceName'],
    );
    expect(maidCafeActionTemplateVariables('echo "no templates"'), isEmpty);
    expect(
      maidCafeActionTemplateVariables('echo {{my-var}} {{ with spaces }}'),
      ['my-var', 'with spaces'],
    );
  });

  test(
    'actions serialize cwd, user and environment into the daemon config',
    () {
      final script = buildMaidCafeDaemonConfigScript(
        daemonId: 'maidkit-1',
        cloudUrl: '',
        cloudSecret: '',
        transport: 'http',
        actions: const [
          MaidCafeActionDefinition(
            name: 'deploy',
            script: 'systemctl restart myapp',
            displayName: 'Deploy the web app',
            workingDirectory: '/srv/myapp',
            user: 'deploy',
            environment: {'CI_BUILD': '42', 'NODE_ENV': 'production'},
          ),
        ],
      );

      final config = decodeMaidCafeConfigFromScript(script);
      expect(config, contains('displayName = "Deploy the web app"'));
      expect(config, contains('cwd = "/srv/myapp"'));
      expect(config, contains('user = "deploy"'));
      expect(config, contains('env = ["CI_BUILD=42", "NODE_ENV=production"]'));
    },
  );

  test('actions without a display name omit the field', () {
    final script = buildMaidCafeDaemonConfigScript(
      daemonId: 'maidkit-1',
      cloudUrl: '',
      cloudSecret: '',
      transport: 'http',
      actions: const [
        MaidCafeActionDefinition(name: 'backup', script: 'echo hi'),
      ],
    );
    final config = decodeMaidCafeConfigFromScript(script);
    expect(config, isNot(contains('displayName')));
  });

  test(
    'run-as users install a sudoers rule and relax the actions directory',
    () {
      final script = buildMaidCafeDaemonInstallScript(
        daemonId: 'daemon-1',
        cloudUrl: '',
        cloudSecret: '',
        artifactUrl: 'https://dist.example/maidcafe-daemon.tar',
        actions: const [
          MaidCafeActionDefinition(
            name: 'deploy',
            script: 'echo hi',
            user: 'deploy',
          ),
          MaidCafeActionDefinition(
            name: 'backup',
            script: 'echo hi',
            user: 'www-data',
          ),
          MaidCafeActionDefinition(name: 'plain', script: 'echo hi'),
        ],
      );

      // The daemon renders substituted scripts into the actions directory, so
      // it must be group-writable; .run is pre-created for it.
      expect(
        script,
        contains(
          'install -d -o root -g maidcafe -m 0770 /etc/maidcafe/actions',
        ),
      );
      expect(
        script,
        contains(
          'install -d -o root -g maidcafe -m 0770 /etc/maidcafe/actions/.run',
        ),
      );
      // The sudoers rule names exactly the distinct run-as users, validated
      // with visudo before install; the rule user is the daemon account.
      expect(script, contains('rule_user="maidcafe"'));
      expect(
        script,
        contains(
          '"\$rule_user ALL=(deploy,www-data) NOPASSWD: '
          '/etc/maidcafe/actions/.run/*, /etc/maidcafe/actions/*"',
        ),
      );
      expect(script, contains('visudo -cf'));
      expect(
        script,
        contains(
          'install -o root -g root -m 0440 "\$sudoers_tmp" '
          '/etc/sudoers.d/maidcafe-actions',
        ),
      );
      // sudo needs its setuid bit for user switching; the unit drops the
      // NoNewPrivileges hardening when a run-as user is configured.
      expect(script, isNot(contains('NoNewPrivileges=true')));
      expect(script, contains('# NoNewPrivileges'));
    },
  );

  test(
    'without run-as users the unit keeps NoNewPrivileges and no sudoers',
    () {
      final script = buildMaidCafeDaemonInstallScript(
        daemonId: 'daemon-1',
        cloudUrl: '',
        cloudSecret: '',
        artifactUrl: 'https://dist.example/maidcafe-daemon.tar',
        actions: const [
          MaidCafeActionDefinition(name: 'plain', script: 'echo hi'),
        ],
      );

      expect(script, contains('NoNewPrivileges=true'));
      expect(
        script,
        contains('install -d -o root -g root -m 0755 /etc/maidcafe/actions'),
      );
      expect(script, isNot(contains('visudo')));
      expect(script, contains('rm -f /etc/sudoers.d/maidcafe-actions'));
    },
  );

  test('stdio run-as rules name the SSH user through SUDO_USER', () {
    final script = buildMaidCafeDaemonInstallScript(
      daemonId: 'daemon-1',
      cloudUrl: '',
      cloudSecret: '',
      artifactUrl: 'https://dist.example/maidcafe-daemon.tar',
      transport: 'stdio',
      actions: const [
        MaidCafeActionDefinition(
          name: 'deploy',
          script: 'echo hi',
          user: 'deploy',
        ),
      ],
    );

    expect(script, contains('rule_user="\${SUDO_USER:-\$(id -un)}"'));
    expect(
      script,
      contains(
        '"\$rule_user ALL=(deploy) NOPASSWD: '
        '/etc/maidcafe/actions/.run/*, /etc/maidcafe/actions/*"',
      ),
    );
    // The actions directory belongs to the SSH user, not the maidcafe
    // service account that does not exist in stdio mode.
    expect(
      script,
      contains('chown "\${SUDO_USER:-\$(id -un)}" /etc/maidcafe/actions'),
    );
    expect(
      script,
      contains(
        'install -d -o "\${SUDO_USER:-\$(id -un)}" -g root -m 0770 '
        '/etc/maidcafe/actions/.run',
      ),
    );
  });

  test(
    'rejects relative working directories and malformed run-as settings',
    () {
      expect(
        () => buildMaidCafeDaemonConfigScript(
          daemonId: 'maidkit-1',
          cloudUrl: '',
          cloudSecret: '',
          transport: 'http',
          actions: const [
            MaidCafeActionDefinition(
              name: 'deploy',
              script: 'echo hi',
              workingDirectory: 'srv/myapp',
            ),
          ],
        ),
        throwsArgumentError,
      );
      expect(
        () => buildMaidCafeDaemonConfigScript(
          daemonId: 'maidkit-1',
          cloudUrl: '',
          cloudSecret: '',
          transport: 'http',
          actions: const [
            MaidCafeActionDefinition(
              name: 'deploy',
              script: 'echo hi',
              user: 'bad user!',
            ),
          ],
        ),
        throwsArgumentError,
      );
      expect(
        () => buildMaidCafeDaemonConfigScript(
          daemonId: 'maidkit-1',
          cloudUrl: '',
          cloudSecret: '',
          transport: 'http',
          actions: const [
            MaidCafeActionDefinition(
              name: 'deploy',
              script: 'echo hi',
              environment: {'1BAD': 'value'},
            ),
          ],
        ),
        throwsArgumentError,
      );
    },
  );

  test('copyWith clears and sets nullable execution fields', () {
    const action = MaidCafeActionDefinition(
      name: 'deploy',
      script: 'echo hi',
      workingDirectory: '/srv/app',
      user: 'deploy',
      environment: {'A': '1'},
    );
    final cleared = action.copyWith(workingDirectory: null, user: null);
    expect(cleared.workingDirectory, isNull);
    expect(cleared.user, isNull);
    expect(cleared.environment, {'A': '1'});
    final changed = action.copyWith(workingDirectory: '/srv/other');
    expect(changed.workingDirectory, '/srv/other');
    expect(changed.user, 'deploy');
    final envChanged = action.copyWith(environment: {'B': '2'});
    expect(envChanged.environment, {'B': '2'});
    expect(envChanged.workingDirectory, '/srv/app');
  });
}
