import 'dart:convert';

/// One directory the MaidCafe daemon's file API may serve, and whether writing
/// inside it needs root.
///
/// The daemon keeps two allowlists that must agree for a privileged root: its
/// own `[[daemon.files.roots]]` entry, and a profile in the helper's
/// `/etc/maidkit/priv.toml`. Both are generated from this one declaration so an
/// operator cannot end up with a root the daemon will route to the helper but
/// the helper refuses, or the reverse.
class MaidCafeFileRoot {
  const MaidCafeFileRoot({
    required this.path,
    this.privileged = false,
    this.profile = '',
    this.modes = const ['0644', '0640'],
  });

  /// Absolute path on the host.
  final String path;

  /// Whether writes inside it go through the `maidkit-priv` helper as root.
  final bool privileged;

  /// The helper profile name authorizing a privileged root. Required when
  /// [privileged]; ignored otherwise.
  final String profile;

  /// The permission modes the helper may use in this root. Only the helper's
  /// supported set is allowed (`0600`, `0640`, `0644`, `0700`, `0750`, `0755`);
  /// the helper refuses anything else, so a value outside it is a configuration
  /// error rather than a silent downgrade.
  final List<String> modes;

  bool get isValid {
    if (path.trim().isEmpty || !path.startsWith('/')) return false;
    if (!privileged) return true;
    if (!RegExp(r'^[a-z0-9][a-z0-9_-]{0,63}$').hasMatch(profile)) return false;
    return modes.isNotEmpty && modes.every(_allowedModes.contains);
  }

  static const _allowedModes = {
    '0600',
    '0640',
    '0644',
    '0700',
    '0750',
    '0755',
  };
}

/// Renders the daemon's `[daemon.files]` table for [roots].
///
/// Every root is a table, never a bare path: a privileged root needs a profile
/// name beside it, and one shape for both kinds keeps this generator honest.
///
/// A null [roots] means the caller has no opinion — it does not model the file
/// API — and renders nothing; the install then carries an existing
/// `[daemon.files]` table over rather than dropping it. An empty list is an
/// explicit "serve nothing" and renders nothing either, but the privileged
/// helper's grant is revoked for it (see [buildMaidCafePrivScript]): the
/// difference between "I did not say" and "I said none" decides whether an
/// operator's own configuration survives an unrelated save.
String maidCafeFilesConfig(List<MaidCafeFileRoot>? roots) {
  final valid = roots?.where((root) => root.isValid).toList() ?? const [];
  if (valid.isEmpty) return '';
  final buffer = StringBuffer()
    ..writeln('[daemon.files]')
    ..writeln('enabled = true')
    // Writing is the interesting half of this feature, so it is on by default
    // here; a read-only root is an operator's deliberate choice, not the
    // default a generated config should make.
    ..writeln('allowWrite = true')
    ..writeln('privilegedHelper = ${_toml('/usr/local/libexec/maidkit-priv')}');
  for (final root in valid) {
    buffer
      ..writeln()
      ..writeln('[[daemon.files.roots]]')
      ..writeln('path = ${_toml(root.path)}');
    if (root.privileged) {
      buffer
        ..writeln('privileged = true')
        ..writeln('profile = ${_toml(root.profile)}');
    }
  }
  return buffer.toString();
}

/// Renders the helper's profile file for the privileged [roots].
///
/// Only privileged roots appear: an unprivileged root is served by the daemon's
/// own account and must not be reachable through the helper, which runs as
/// root.
String maidCafePrivToml(List<MaidCafeFileRoot> roots) {
  final privileged = roots
      .where((root) => root.privileged && root.isValid)
      .toList();
  if (privileged.isEmpty) return '';
  final buffer = StringBuffer()
    ..writeln('# Generated by MaidKit. This file is the authorization boundary for')
    ..writeln('# privileged file writes: the sudoers rule authorizes the helper, and')
    ..writeln('# the helper can only reach the directories named here. Keep it root-owned')
    ..writeln('# and unwritable by anyone else.')
    ..writeln();
  for (final root in privileged) {
    buffer
      ..writeln('[[profiles]]')
      ..writeln('name = ${_toml(root.profile)}')
      ..writeln('path = ${_toml(root.path)}')
      ..writeln(
        'modes = [${root.modes.map(_toml).join(', ')}]',
      )
      ..writeln();
  }
  return buffer.toString();
}

/// Builds the privileged shell snippet that installs the `maidkit-priv` helper,
/// its profile file and the sudoers rule authorizing it.
///
/// Ordering is load-bearing, and this script is the authority on it: the helper,
/// the profiles and the rule are installed **before** the daemon configuration
/// that declares a privileged root, because the daemon validates that its
/// helper exists when it loads its configuration. The caller therefore runs this
/// before writing `config.toml`.
///
/// The sudoers rule is printed by the installed helper itself (`maidkit-priv
/// sudoers` with the account as its argument), so the rule and the helper's command surface cannot
/// drift apart, and `visudo` validates it before it is installed — the same
/// gate the run-as rule uses. With no privileged roots the rule and the profile
/// file are removed: a helper that can reach nothing is one thing, but a
/// standing sudoers grant is what should not survive.
///
/// [helperBase64] is the compiled helper's bytes. It is null when the caller has
/// no bundle for this platform (the helper ships with the daemon archive on
/// Linux and macOS); the script then keeps any installed helper and only
/// reconciles the profiles and the rule.
String buildMaidCafePrivScript(
  List<MaidCafeFileRoot>? roots, {
  required bool stdio,
  String? helperBase64,
}) {
  final privileged = roots
          ?.where((root) => root.privileged && root.isValid)
          .toList() ??
      const <MaidCafeFileRoot>[];
  // The daemon runs as the SSH user in stdio mode; sudo sets SUDO_USER when the
  // install was elevated, so that is the account the rule must name. The
  // expression is evaluated by the install script, not written literally.
  final ruleUserExpr = stdio ? '"\${SUDO_USER:-\$(id -un)}"' : '"maidcafe"';
  const helperPath = '/usr/local/libexec/maidkit-priv';
  const configPath = '/etc/maidkit/priv.toml';

  // Installed through /dev/stdin, the same way action scripts are, so no
  // temporary file exists for another account to race.
  final installHelper = helperBase64 == null
      ? ''
      : "printf '%s' '$helperBase64' | base64 -d | "
            'install -o root -g root -m 0755 /dev/stdin $helperPath';

  // A caller that does not model file roots says nothing about them, and
  // removing a grant this save did not create would revoke a feature the
  // operator configured. Only an explicit empty declaration does that.
  if (roots == null) {
    if (helperBase64 == null) return '';
    return '''
install -d -o root -g root -m 0755 /usr/local/libexec
$installHelper''';
  }
  if (privileged.isEmpty) {
    return '''
rm -f /etc/sudoers.d/maidkit-priv
rm -f $configPath''';
  }

  final encodedToml = base64Encode(utf8.encode(maidCafePrivToml(roots)));
  return '''
command -v visudo >/dev/null 2>&1 || {
  echo "Privileged file roots require visudo (sudo) on the host." >&2
  exit 1
}
install -d -o root -g root -m 0755 /usr/local/libexec /etc/maidkit
$installHelper
if [ ! -x $helperPath ]; then
  echo "The privileged helper is not installed at $helperPath." >&2
  echo "Reinstall the daemon bundle to get maidkit-priv, or declare no privileged roots." >&2
  exit 1
fi
printf '%s' '$encodedToml' | base64 -d | install -o root -g root -m 0644 /dev/stdin $configPath
# Refuse to install a profile file the helper cannot parse, so a typo here
# surfaces during the install rather than as a failed write later.
$helperPath --config $configPath fs profiles >/dev/null || {
  echo "The privileged helper rejected the generated profile file." >&2
  exit 1
}
rule_user=$ruleUserExpr
sudoers_tmp="\$(mktemp "\${TMPDIR:-/tmp}/maidkit-priv.XXXXXX")"
# The rule comes from the helper itself, so it always matches the verbs it
# implements.
"$helperPath" sudoers "\$rule_user" > "\$sudoers_tmp"
visudo -cf "\$sudoers_tmp" >/dev/null 2>&1 || {
  echo "MaidCafe rejected the privileged helper's sudoers rule; no changes were made." >&2
  rm -f "\$sudoers_tmp"
  exit 1
}
install -o root -g root -m 0440 "\$sudoers_tmp" /etc/sudoers.d/maidkit-priv
rm -f "\$sudoers_tmp"''';
}

/// Quotes a TOML basic string, escaping the characters TOML treats specially.
String _toml(String value) {
  final escaped = value
      .replaceAll('\\', '\\\\')
      .replaceAll('"', '\\"')
      .replaceAll('\n', '\\n')
      .replaceAll('\r', '\\r')
      .replaceAll('\t', '\\t');
  return '"$escaped"';
}
